name: Deploy to UAT Environment
on:
  push:
    branches:
      - main

concurrency: uat_environment

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to uat"